export const CREATE_CHATROOM_STARTED = 'CREATE_CHATROOM_STARTED'
export const CREATE_CHATROOM_COMPLETED = 'CREATE_CHATROOM_COMPLETED'
export const CREATE_CHATROOM_FAILED = 'CREATE_CHATROOM_FAILED'

export const FETCH_CHATROOMS_STARTED = 'FETCH_CHATROOMS_STARTED'
export const FETCH_CHATROOMS_COMPLETED = 'FETCH_CHATROOMS_COMPLETED'
export const FETCH_CHATROOMS_FAILED = 'FETCH_CHATROOMS_FAILED'
