export const THEME_SET_STARTED = 'THEME_SET_STARTED'
export const THEME_SET_COMPLETED = 'THEME_SET_COMPLETED'
export const THEME_SET_FAILED = 'THEME_SET_FAILED'

export const THEME_GET_STARTED = 'THEME_GET_STARTED'
export const THEME_GET_COMPLETED = 'THEME_GET_COMPLETED'
export const THEME_GET_FAILED = 'THEME_GET_FAILED'